### ISSUE TITLE
Error 401 Unauthorised on logintoken POST

### ISSUE THREAD

**Issue by jonybur** [david-asher/electron-firebase#5]
Hey all. I'm trying to set up a simple log in screen using Google authentication, but I get a 401 error when reaching the `postAuthResult` function on `weblogin.js`. The odd thing is that `appUpdate` seems to be fully populated with correct data, and `firebase.auth().currentUser` is filled properly as well, therefore the log in went through successfully (I assume).
Unfortunately the POST to /api/logintoken fails with a 401 Unauthorised error, without any other explanation. I rechecked my firebase config and google cloud configuration and everything seems to be in order and properly set up. Any ideas about what could be the cause of the problem?
Thank you

**Comment by david-asher** [comment]
You are correct that the Google authentication completed successfully. The 401 Unauthorized error comes from the Main electron process. After the Google login, the browser POSTs the login results to an HTTPS server hosted by Main in order to keep this information private. The error is generated from the signInNewUser function (authentication.js) where the Main process attempts to take the Google login credentials and login again for the Main process itself, which requires a small Firebase Cloud Function to bounce back user credentials through the customToken process. My best guess is that there was an error in getting this set up. Please go back to the documentation section "Enable Firebase Custom Tokens" and make sure that this process succeeds. As a result, you should be able to look at your Firebase dashboard, Project Overview -> Build -> Functions and see customToken to confirm this is installed correctly.
