### ISSUE TITLE
Error in Deploying Firestore:rules

### ISSUE THREAD

**Issue by Calhistorian** [david-asher/electron-firebase#6]
Just attempting to run setup electron-firestore and test out the example apps, I run into an error when running 'npm run deploy' in deploying the Security Rules and Cloud Functions. Attempting through a clean cloud project. 

```
=== Deploying to 'app_name'...

i  deploying firestore
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  firestore: uploading rules firestore.rules...

Error: HTTP Error: 400, Request contains an invalid argument.
child_process.js:682
    throw err;
    ^

Error: Command failed: firebase deploy --only firestore:rules
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at fbDeploy (/Users/calhistorian20/Github/electron-firebase/config/firebase-deploy.js:38:5)
    at /Users/calhistorian20/Github/electron-firebase/config/firebase-deploy.js:73:5
    at Object.<anonymous> (/Users/calhistorian20/Github/electron-firebase/config/firebase-deploy.js:84:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5525,
  stdout: null,
  stderr: null
}
```

Alternatively, and I don't know if it is related, the `databaseURL` is no longer provided in the firebase SDK (under project settings), perhaps due to the development of Cloud Firestore as opposed to the older Realtime Firestore.

**Comment by david-asher** [comment]
Hi Mark, I will take a look at this issue tomorrow (Monday) and hope to get you a response by the end of day. In the meantime, please check that your Firebase account is set to the Blaze level.

**Comment by david-asher** [comment]
The parameter databaseURL is never used in this project, so that's a red herring.

Here are some things to check:
1. From a command line at the project root folder, you should be able to run "firebase login" and successfully login with your firebase credentials.
2. The project root folder should have a file ".firebaserc". Open it and check that the "projects" object has a "default" parameter which has been set to your firebase project name. 
3. From the command line at project root, run ""firebase deploy --only firestore:rules". I expect this to fail but we may get more detailed error information.
4. Take a look at your firebase console [https://console.firebase.google.com](https://console.firebase.google.com) and for your project look at "Firestore database" and "Rules".  It should be possible to deploy the config/cloud-firestore.rules file directly from your firebase console. If that fails then it's far more likely that the problem is with the configuration of firebase than on the client side.

Please send an update with more information.

**Comment by Calhistorian** [comment]
Ok. So I started from scratch again. Went through all the steps. 
1. Yes, login was never an issue.
2. .firebaseerc is set to project name.
3. This is the error I get from doing this:
`Error: HTTP Error: 404, Requested entity was not found.`
4. I went ahead and manually uploaded the rules.

I went ahead and just fired up the app using `npm start` and it opens but the "firebase spinner" just continues to spin. I am assuming this is the login window (of which I have only Google Signin setup on the project). 

My application is currently in development and I have just been using google service accounts for testing purposes, I hope to use this as a model for authentication as well as access to other cloud functions.

**Comment by david-asher** [comment]
I just tried a fresh install and the deploy and start actions worked perfectly EXCEPT the login embedded in the deploy script failed. The firebase login command defaulted to a non-interactive mode and that failed, and I'd like to test whether that's also happening in your case but maybe in your setup you are not seeing the error. Please try this: edit file ./config/firebase-deploy.js and change line 65 to be the following.

> execSync( "firebase login --interactive", {stdio:'inherit'} )

Then try 

> npm run deploy

**Comment by Calhistorian** [comment]
Still get this error:

```
Error: HTTP Error: 404, Requested entity was not found.
child_process.js:682
    throw err;
    ^

Error: Command failed: firebase deploy --only firestore:rules
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at fbDeploy (/.../.../.../electron-firebase/config/firebase-deploy.js:38:5)
    at /.../.../...electron-firebase/config/firebase-deploy.js:73:5
    at Object.<anonymous> (/.../.../.../electron-firebase/config/firebase-deploy.js:84:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9560,
  stdout: null,
  stderr: null
}
```

This is definitely the clearest template out there to follow, I will try again tomorrow with a fresh Cloud project (again) and make the change you suggest above. 

When I originally posted, I was on firebase-tools 9.16.0, but now I am using 9.20.0. I might also try it on my iMac. As perhaps my configuration is faulty on my laptop.

**Comment by david-asher** [comment]
I know it's tedious and you've been very careful, but it is starting to look like a configuration problem on the Firebase side. At least the error is before the app runs so we don't need to focus on the authentication provider setup - that limits the possible errors. I'd suggest paying particular attention to the IAM setup. The 404 error code may be misleading if it's a permission problem in the first place. 

There are a bunch of 404 references on StackOverflow relating to older versions of firebase tools. Had you been using firebase for a while and might have an older version of firebase-tools installed?

Or if you have multiple projects, you may need to set the project with the command "firebase use [project-id]" as described in this report: https://stackoverflow.com/questions/62929940/firebase-hosting-deployment-error-error-error-404-requested-entity-was-not-fo

**Comment by Calhistorian** [comment]
Hmmm... So I used the `firebase use --add` solution and it passed the previous 404....

Now errored out on:

```
Project Console: https://console.firebase.google.com/project/edn2sheets-319721/overview
** deploy storage:rules
/.../electron-firebase/config/firebase-deploy.js:77
    fbDeployJson.storage[0].bucket = fbConfig.storageBucket
                                   ^

TypeError: Cannot set property 'bucket' of undefined
    at /.../electron-firebase/config/firebase-deploy.js:77:36
    at Object.<anonymous> (/.../electron-firebase/config/firebase-deploy.js:84:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
    ```

Which may still be related to my configuration....

**Comment by david-asher** [comment]
That's a failure to read the file "firebase.json" which should have been copied into your project root folder at installation time, from the ./install_app/postinstall.js script. To save time testing this, rather than performing a fresh installation, just issue this:

> npm run postinstall

But first, there's a reason why that file didn't copy, maybe a permission error on the project root folder. What platform are you on? You should be able to make this installation work without sudo on linux, but both Mac and Windows may have permissions challenges depending on where you install. In any case, you'll need to solve this until the postinstall script runs and leaves the firebase.json file in the project root folder.
